deployment:
  tasks:
    - export DEPLOYPATH=/home2/xxxx/public_html/portfolio/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH